title: LangSim
author: Jan Janssen

execute:
  execute_notebooks           : off

repository:
    url                       : https://github.com/jan-janssen/langsim
    path_to_book              : ""

launch_buttons:
  notebook_interface          : jupyterlab
  binderhub_url               : https://mybinder.org