name: Jupyterbook

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Conda config
      run: echo -e "channels:\n  - conda-forge\n" > .condarc
    - uses: conda-incubator/setup-miniconda@v3
      with:
        python-version: "3.11"
        condarc-file: .condarc
        miniforge-version: latest
    - name: Install Jupyterbook
      shell: bash -l {0}
      run: |
        conda install -y -c conda-forge jupyter-book 
        jupyter-book build . --path-output public
    - run: mv public/_build/html public_html
    - run: touch public_html/.nojekyll