name: Unittests

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        include:
          - operating-system: macos-latest
            python-version: '3.12'

          - operating-system: ubuntu-latest
            python-version: '3.12'

          - operating-system: ubuntu-latest
            python-version: '3.11'

          - operating-system: ubuntu-latest
            python-version: '3.10'

    steps:
    - uses: actions/checkout@v4
    - name: Conda config
      run: echo -e "channels:\n  - conda-forge\n" > .condarc
    - name: Setup Mambaforge
      uses: conda-incubator/setup-miniconda@v3
      with:
        python-version: ${{ matrix.python-version }}
        environment-file: environment.yml
        condarc-file: .condarc
        miniforge-version: latest
    - name: Test
      shell: bash -l {0}
      timeout-minutes: 6
      run: |
        pip install . --no-deps --no-build-isolation
        python -m unittest discover tests
